server:
  port: 10050
spring:
  application:
    name: service-course #服务名
  cloud: #注册到Nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///tigercc-course?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 使用ali的连接池
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
mybatis-plus:
  mapper-locations: classpath:org/yjhking/tigercc/mapper/*Mapper.xml # 指定mapper.xml位置
  type-aliases-package: org.yjhking.tigercc.domain,org.yjhking.tigercc.query # 配置别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志
file:
  alicloud:
    bucket-name: tigercc #上传空间bucket
    access-key: LTAI5tJYNf343fNHhNrQ4eCA #你的key
    secret-key: ZPsCWRdRtKGNnZtkL37OKU6pMcImaI #你的秘钥
    endpoint: oss-cn-chengdu.aliyuncs.com  #上传端点
feign:
  sentinel:
    enabled: true # 开启熔断功能
  compression:
    request:
      enabled: true
      min-request-size: 1024 # 最小阈值，小于这个不压缩
      mime-types: text/xml,application/xml,application/json # 压缩哪些类型的数据
    response:
      enabled: true
rocketmq:
  name-server: 127.0.0.1:9876
  #生产者配置
  producer:
    #生产者组名字
    group: "service-course-producer"
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 30000
    # 发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
tigercc:
  message:
    content: "新课上线 %s，<a href='http://course.tigercc.com/detial.html?courseId=%s'>点击查看</a>"
    title: "课程发布了"
    type: "课程消息"