server:
  port: 10060
spring:
  application:
    name: service-file #服务名
  cloud: #注册到Nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8