server:
  port: 10080
spring:
  application:
    name: service-search #服务名
  cloud: #注册到Nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://localhost:9200